# Individual voting rewards
voting:
  message: "<#1aff1a>Thank you for voting! <#ff1a1a>Here are your rewards."
  # %player% is replaced with the player's name
  rewards:
    - "crate key give %player% vote 1"

# Vote party rewards
voteparty:
  message: "<#1aff1a>Vote party! <#ff1a1a>Everyone gets a reward."
  totalvotes: 25
  # "individual" - rewards given to each player | "server-wide" - rewards given to entire server
  rewardType: "individual"
  rewards:
    - "crate key give %player% vote 1"